spring:
  profiles:
    active:
      - cat
      - EN
      - qa

guru:
  username: YmlUserName
  password: YmlPassword
  jdbcurl: someUrlForDB

---
spring:
  profiles: prod
guru:
  username: YmlProdUserName
  password: YmlProdPassword
  jdbcurl: YmlProdUrlForDB
#spring:
#  config:
#    activate:
#      on-profile:   prod
